(defsystem :aoc.requirements
  :depends-on ("alexandria"
               "bordeaux-threads"
               "coalton"
               "cl-ppcre"
               "cl-algebraic-data-type"
               "drakma"
               "esrap"
               "lparallel"
               "local-time"
               "local-time-duration"
               "series"
               "trivia"
               "trivia.quasiquote"
               "uiop"))
